method:
  name : "DDPO"

model:
  model_path: "stabilityai/stable-diffusion-2-1-base"
  model_arch_type: "LDMUnet"
  attention_slicing: True
  xformers_memory_efficient: True
  gradient_checkpointing: True

sampler:
  num_inference_steps: 50

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-5
    weight_decay: 1.0e-4
    betas: [0.9, 0.999]

scheduler:
  name: "linear" # Name of learning rate scheduler
  kwargs:
    start_factor: 1.0
    end_factor: 1.0
  
logging:
  run_name: 'ddpo_sd_imagenet'
  wandb_project: 'DRLX'

train:
  num_epochs: 200
  num_samples_per_epoch: 256
  batch_size: 4
  sample_batch_size: 32
  grad_clip: 1.0
  checkpoint_interval: 50
  tf32: True
  suppress_log_keywords: "diffusers.pipelines,transformers"
  save_samples: False